### PR TITLE
Eileen Eddy's Sprint Challenge Responsive-Less with Stretch and Super Stretch completed

### PR DESCRIPTION
**Pull request by algorithmsrock**

### CODE REVIEW

**Comment by wlharvey4** [comment]
Eileen,
Nice job; very good answers provided-thank you for working hard on those.

Your coding is marvelous.  I would suggest you make far more commits than you have done.  Each commit should be limited to a specific problem or issue; then give a title to the commit, followed by a blank line, followed by the body of your commit message, which will have details about the commit.  Keep lines to 72 characters or less.  Doing this will allow a code reviewed looking  for bugs or a specific issue to address to easily and quickly find it.  With all changes lumped into just a few commits with no details, that job becomes a lot harder and longer.

This not to detract from the obvious hard work you put into this project, but to take your skills to the next level.  Great job.

Wesley

**Comment by mixelpixel** [comment]
Images from Eileen demonstrated what appears to be an Edge specific bug with her code:

image uploaded from ios

image uploaded from ios_1

**Eileen Eddy [2:23 PM]**
> When it gets to be 1100 px it stops separating them
> But works exactly correctly for smaller sizes

image uploaded from ios_2

**Eileen Eddy [2:24 PM]**
> Vs Firefox and Chrome that work correctly

**Comment by wlharvey4** [comment]
I opened your project in Safari.  It looks to work correctly.

**Comment by wlharvey4** [comment]
screen shot 2018-02-05 at 12 13 00 pm

**Comment by wlharvey4** [comment]
screen shot 2018-02-05 at 12 13 27 pm

**Comment by wlharvey4** [comment]
screen shot 2018-02-05 at 12 13 58 pm

**Pull request closed without merging**
